on: push
name: Import test
jobs:
  cjs:
    name: CommonJS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - windows-latest
        nodejs:
        - "10.0.0"
      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Output versions
      run: node -v
    - name: Run!
      run: node ./main/*.js
  esm:
    name: ES Modules with extensions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - windows-latest
        nodejs:
        - "10.0.0"
      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Output versions
      run: node -v
    - name: Run!
      run: node --experimental-modules ./main/*.mjs
